In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Datasets\heart.csv')
data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
data.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [4]:
to_encode = ["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"]

In [5]:
dummies = pd.get_dummies(data[to_encode])

In [6]:
dummies.columns

Index(['Sex_F', 'Sex_M', 'ChestPainType_ASY', 'ChestPainType_ATA',
       'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_LVH',
       'RestingECG_Normal', 'RestingECG_ST', 'ExerciseAngina_N',
       'ExerciseAngina_Y', 'ST_Slope_Down', 'ST_Slope_Flat', 'ST_Slope_Up'],
      dtype='object')

In [7]:
dummies

,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,False,True,False,True,False,False,False,True,False,True,False,False,False,True
1,True,False,False,False,True,False,False,True,False,True,False,False,True,False
2,False,True,False,True,False,False,False,False,True,True,False,False,False,True
3,True,False,True,False,False,False,False,True,False,False,True,False,True,False
4,False,True,False,False,True,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,False,True,False,False,False,True,False,True,False,True,False,False,True,False
914,False,True,True,False,False,False,False,True,False,True,False,False,True,False
915,False,True,True,False,False,False,False,True,False,False,True,False,True,False
916,True,False,False,True,False,False,True,False,False,True,False,False,True,False
917,False,True,False,False,True,False,False,True,False,True,False,False,False,True

In [8]:
dummies.drop(
    [
        "Sex_F",
        "ChestPainType_TA",
        "RestingECG_ST",
        "ExerciseAngina_N",
        "ST_Slope_Down",
    ],
    axis=1,
    inplace=True,
)

In [9]:
dummies

,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,RestingECG_LVH,RestingECG_Normal,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,True,False,True,False,False,True,False,False,True
1,False,False,False,True,False,True,False,True,False
2,True,False,True,False,False,False,False,False,True
3,False,True,False,False,False,True,True,True,False
4,True,False,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...
913,True,False,False,False,False,True,False,True,False
914,True,True,False,False,False,True,False,True,False
915,True,True,False,False,False,True,True,True,False
916,False,False,True,False,True,False,False,True,False
917,True,False,False,True,False,True,False,False,True

In [10]:
data

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [11]:
data.drop(
    [
        "Sex",
        "ChestPainType",
        "RestingECG",
        "ExerciseAngina",
        "ST_Slope",
        "FastingBS"
    ], axis=1, inplace=True
)

In [12]:
data

     Age  RestingBP  Cholesterol  MaxHR  Oldpeak  HeartDisease
0     40        140          289    172      0.0             0
1     49        160          180    156      1.0             1
2     37        130          283     98      0.0             0
3     48        138          214    108      1.5             1
4     54        150          195    122      0.0             0
..   ...        ...          ...    ...      ...           ...
913   45        110          264    132      1.2             1
914   68        144          193    141      3.4             1
915   57        130          131    115      1.2             1
916   57        130          236    174      0.0             1
917   38        138          175    173      0.0             0

[918 rows x 6 columns]

In [13]:
X = data.drop("HeartDisease", axis=1)
y = data.HeartDisease
X = pd.concat([X, dummies], axis=1)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=10
)

In [15]:
X_train

,Age,RestingBP,Cholesterol,MaxHR,Oldpeak,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,RestingECG_LVH,RestingECG_Normal,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
524,55,150,160,150,0.0,True,True,False,False,False,False,False,False,True
225,50,145,264,150,0.0,True,True,False,False,False,True,False,True,False
280,60,120,246,135,0.0,True,False,False,True,True,False,False,False,True
94,39,110,182,180,0.0,False,False,False,True,False,False,False,False,True
586,53,124,243,122,2.0,True,True,False,False,False,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,63,150,0,86,2.0,True,True,False,False,False,True,True,True,False
320,59,125,0,175,2.6,True,False,False,True,False,True,False,True,False
527,61,139,283,135,0.3,True,False,True,False,False,True,False,False,True
125,54,120,246,110,0.0,True,False,True,False,False,True,False,False,True
265,54,160,305,175,0.0,True,False,True,False,False,True,False,False,True

In [16]:
X_train.shape

(734, 14)

In [17]:
num = ["Age", "RestingBP", "Cholesterol", "MaxHR", "Oldpeak"]
cat = [
    "Sex_M",
    "ChestPainType_ASY",
    "ChestPainType_ATA",
    "ChestPainType_NAP",
    "RestingECG_LVH",
    "RestingECG_Normal",
    "ExerciseAngina_Y",
    "ST_Slope_Flat",
    "ST_Slope_Up",
]

(734, 14)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

(734, 5)
(734, 9)

In [19]:
# Scale numerical features and reset indices
X_train_scaled_num = pd.DataFrame(scaler.fit_transform(X_train[num]), columns=X_train[num].columns).reset_index(drop=True)
X_train_cat = X_train[cat].reset_index(drop=True)

# Concatenate the scaled numerical features with the categorical features
X_train_scaled = pd.concat([X_train_scaled_num, X_train_cat], axis=1)
print(X_train_scaled.shape)

# Similarly, for the test set
X_test_scaled_num = pd.DataFrame(scaler.transform(X_test[num]), columns=X_test[num].columns).reset_index(drop=True)
X_test_cat = X_test[cat].reset_index(drop=True)

X_test_scaled = pd.concat([X_test_scaled_num, X_test_cat], axis=1)
print(X_test_scaled.shape)

(734, 14)
(184, 14)

In [20]:
X_train_scaled.shape

(734, 14)

In [21]:
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

model_params = {
    "svm": {
        "model": SVC(gamma="auto"),
        "params": {"C": [1, 5, 10], "kernel": ["rbf", "linear", "poly"]},
    },
    "logistic": {
        "model": LogisticRegression(
            solver="liblinear", multi_class="auto", max_iter=500
        ),
        "params": {"C": [1, 5, 10]},
    },
    "xgboost": {
        "model": XGBClassifier(),
        "params": {
            "n_estimators": [25, 50, 75, 100],
            "learning_rate": [0.01, 0.05, 0.1],
        },
    },
    "randomforest": {
        "model": RandomForestClassifier(),
        "params": {"n_estimators": [10, 30, 50]},
    },
}

scores = []
for model_name, mp in model_params.items():
    model = GridSearchCV(mp["model"], mp["params"], cv=5, return_train_score=False)
    model.fit(X_train_scaled, y_train)
    scores.append(
        {
            "model": model_name,
            "best_score": model.best_score_,
            "best_params": model.best_estimator_,
        }
    )

c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [22]:
df = pd.DataFrame(scores, columns = ['model','best_score', 'best_params'])

In [23]:
df

          model  best_score                                        best_params
0           svm    0.873264              SVC(C=1, gamma='auto', kernel='poly')
1      logistic    0.865073  LogisticRegression(C=5, max_iter=500, multi_cl...
2       xgboost    0.859650  XGBClassifier(base_score=None, booster=None, c...
3  randomforest    0.871848  (DecisionTreeClassifier(max_features='sqrt', r...

In [24]:
from sklearn.decomposition import PCA
pca = PCA(n_components=7)

In [25]:
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)
X_train_pca_df = pd.DataFrame(X_train_pca, columns=[f'PC{i+1}' for i in range(X_train_pca.shape[1])])
X_test_pca_df = pd.DataFrame(X_test_pca, columns=[f'PC{i+1}' for i in range(X_test_pca.shape[1])])

# 4. Reset indices of categorical features
X_train_cat_reset = X_train[cat].reset_index(drop=True)
X_test_cat_reset = X_test[cat].reset_index(drop=True)

# 5. Concatenate PCA components with the original categorical features
X_train_scaled = pd.concat([X_train_pca_df, X_train_cat_reset], axis=1)
X_test_scaled = pd.concat([X_test_pca_df, X_test_cat_reset], axis=1)

In [26]:
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

model_params = {
    "svm": {
        "model": SVC(gamma="auto"),
        "params": {"C": [1, 5, 10], "kernel": ["rbf", "linear", "poly"]},
    },
    "logistic": {
        "model": LogisticRegression(
            solver="liblinear", multi_class="auto", max_iter=500
        ),
        "params": {"C": [1, 5, 10]},
    },
    "xgboost": {
        "model": XGBClassifier(),
        "params": {
            "n_estimators": [25, 50, 75, 100],
            "learning_rate": [0.01, 0.05, 0.1],
        },
    },
    "randomforest": {
        "model": RandomForestClassifier(),
        "params": {"n_estimators": [10, 30, 50]},
    },
}

scores = []
for model_name, mp in model_params.items():
    model = GridSearchCV(mp["model"], mp["params"], cv=5, return_train_score=False)
    model.fit(X_train_scaled, y_train)
    scores.append(
        {
            "model": model_name,
            "best_score": model.best_score_,
            "best_params": model.best_estimator_,
        }
    )

c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\jrsak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [27]:
df = pd.DataFrame(scores, columns = ['model','best_score', 'best_params'])
df

          model  best_score                                        best_params
0           svm    0.874616              SVC(C=1, gamma='auto', kernel='poly')
1      logistic    0.865073  LogisticRegression(C=5, max_iter=500, multi_cl...
2       xgboost    0.846016  XGBClassifier(base_score=None, booster=None, c...
3  randomforest    0.863713  (DecisionTreeClassifier(max_features='sqrt', r...